### ISSUE TITLE
problems with the button

### ISSUE THREAD

**Issue by isdito** [b31ngD3v/instagram-auto-dm#2]
hello,

I have problems with the button

```
Traceback (most recent call last):
  File "mensaje_dm.py", line 91, in <module>
    dmer()
  File "mensaje_dm.py", line 74, in dmer
    send_msg(usrnamee)
  File "mensaje_dm.py", line 67, in send_msg
    snd_btnn.click()
  File "C:\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button class="sqdOP yWX7d    y3zKF     " type="button">...</button> is not clickable at point (923, 909). Other element would receive the click: <div class="rh7Wz">...</div>
  (Session info: chrome=87.0.4280.88)

```

**Comment by isdito** [comment]
Hello.

The problem it is the text it is more large... I can not resolve

#txt_box.send_keys("este año ha sido terrible en nuestro sector y hemos tenido que dividirnos.")
#txt_box.send_keys("Pero estamos seguros que @{newbornvalencia} conseguirá despegar con vuestra ayuda.")  
#txt_box.send_keys("A todos nuestros Camaradas, compatriotas, seguidores, amantes, aventureros por favor seguir  @{newbornvalencia}. ")  
#txt_box.send_keys("Besos y Abrazos")
